### ISSUE TITLE
Can't seem to use TLS

### ISSUE THREAD

**Issue by sntran** [nullobsi/ftpdeno#13]
When trying to connect to an FTP server with TLS, I encounter issue with `Deno.startTls`.

Example:

```ts
import { FTPClient } from "https://raw.githubusercontent.com/nullobsi/ftpdeno/main/mod.ts";

const client = new FTPClient("ftp.dlptest.com", {
  user: "dlpuser",
  pass: "rNrKYTX9g7z3RgJRmxWuGHbeu",
  port: 21,
  tlsOpts: {
  }
});

await client.connect();
console.log("Connected!");
```

```shell
$ deno run -A ftp.js 
error: Uncaught (in promise) BadResource: TCP stream is currently in use
            this.conn = await Deno.startTls(this.conn, {
                                   ^
    at opStartTls (ext:deno_net/02_tls.js:10:15)
    at Object.startTls (ext:deno_net/02_tls.js:88:57)
    at FTPClient.connect (https://raw.githubusercontent.com/nullobsi/ftpdeno/main/classes/FTPClient.ts:170:27)
    at eventLoopTick (ext:core/01_core.js:178:11)
```

**Comment by nullobsi** [comment]
So, I've spent a couple hours on this but I was unable to find a fix. Essentially the TextLineStream puts the TCP connection "in use." I would think releasing the lock would be enough, but that doesn't help. The most recent commit 0fe6e4d attempts to fix the issue but doesn't work. Some reference:

https://github.com/denoland/deno/blob/1a0fbc4c3cdba5901d4cb096cb1beb828fbc8427/ext/net/ops_tls.rs#L343
https://stackoverflow.com/questions/71262432/how-can-i-close-a-web-serial-port-that-ive-piped-through-a-transformstream

To be honest, I'm not sure if this is a Deno issue or something I'm able to fix. I've combed through the code and debugger but couldn't find how to tell Deno to "release" the TCP connection without closing it.

**Comment by MurmeltierS** [comment]
@nullobsi I had pretty much the same problem for my Cloudflare Worker version, which led me down a weird rabbit-hole where I basically replaced the TextLineStream with a (weird) workaround: 

https://github.com/Brand-Boosting-GmbH/workerd-ftp/blob/4a47c6ba99e05aeab19fc639e6a46232a438a41f/src/classes/ftp-client.ts#L722

I hate every part of it - but it allows for upgrading to TLS.
