### ISSUE TITLE
FtpClient certFile Error

### ISSUE THREAD

**Issue by cfjello** [nullobsi/ftpdeno#5]
Running a slightly updated version of the example in the README file;

```
// Requires --allow-net and --allow-write
import {FTPClient} from "https://deno.land/x/ftpc/mod.ts";

// Connect as anonymous user
const client = new FTPClient("speedtest.tele2.net");
await client.connect();
console.log("Connected!");

// Download test file
console.log("Downloading...");
const file = await Deno.open("./5MB.zip", {
    create: true,
    write: true,
});
const stream = await client.downloadStream("5MB.zip");
await Deno.copy(stream, file);

// Close download stream
await client.finalizeStream();
file.close();
console.log("Finished!")

// Log off server
await client.close();
```

Using the command: `deno run -A .\ftpConnTest.ts`

I get the following TypeScript compile error: 

```
error: TS2345 [ERROR]: Argument of type '{ hostname: string; certFile: string | undefined; }' is not assignable to parameter of type 'StartTlsOptions'.
  Object literal may only specify known properties, and 'certFile' does not exist in type 'StartTlsOptions'.  
                certFile: this.opts.tlsOpts.certFile,
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/ftpc@v1.2.1/classes/FTPClient.ts:82:17

TS2345 [ERROR]: Argument of type '{ certFile: string | undefined; hostname: string; }' is not assignable to parameter of type 'StartTlsOptions'.
  Object literal may only specify known properties, and 'certFile' does not exist in type 'StartTlsOptions'.  
                certFile: this.opts.tlsOpts.certFile,
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/ftpc@v1.2.1/classes/FTPClient.ts:587:17

Found 2 errors.
```

By the way, it seems that Deno has depreciated `Deno.copy()`

Regards, Claus

**Comment by nullobsi** [comment]
Thanks. Deno is fast moving. I'll check it out when I'm free and fix up the API calls :)

**Comment by nullobsi** [comment]
Oh, though it appears this was already fixed in master branch. -> https://github.com/nullobsi/ftpdeno/releases/tag/v1.3.0

**Comment by cfjello** [comment]
Thanks., I forgot to reload.  Now, when running `deno run -A --reload .\ftpConnTest.ts `, I get the following error, not TypeScript related, but only to the README example code itself:

```
error: Uncaught (in promise) ConnectionRefused: No connection could be made because the target machine actively refused it. (os error 10061)
        this.conn = await Deno.connect({
                    ^
    at async Object.connect (deno:ext/net/01_net.js:314:13)
    at async FTPClient.connect (https://deno.land/x/ftpc@v1.3.0/classes/FTPClient.ts:64:21)
```

**Comment by cfjello** [comment]
No reason to keep this open - thanks for the feedback.
